import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="bg-white px-3 py-5">
          <ul className="flex justify-end gap-7 mt-3 mr-3">
            <Link href="/">ホーム</Link>
            <Link href="/blog">スタッフブログ</Link>
            <Link href="/contact">お問い合わせ</Link>
            <Link href="/admin">管理画面</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
